In [3]:
from tqdm.autonotebook import tqdm
%load_ext autoreload
%autoreload 2
from hmm import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[nltk_data] Downloading package indian to
[nltk_data]     /Users/tylercranmer/nltk_data...
[nltk_data]   Package indian is already up-to-date!


In [4]:
words, tags, observation_dict, state_dict, observation_ids, state_ids = get_hindi_dataset()

In [5]:
state_dict

{'': 0,
 'CC': 1,
 'INTF': 2,
 'JJ': 3,
 'JVB': 4,
 'NEG': 5,
 'NLOC': 6,
 'NN': 7,
 'NNC': 8,
 'NNP': 9,
 'NNPC': 10,
 'NVB': 11,
 'PREP': 12,
 'PRP': 13,
 'PUNC': 14,
 'QF': 15,
 'QFNUM': 16,
 'QW': 17,
 'RB': 18,
 'RP': 19,
 'SYM': 20,
 'VAUX': 21,
 'VFM': 22,
 'VJJ': 23,
 'VNN': 24,
 'VRB': 25}

In [7]:
    # def decode(self, observation_ids: List[List[int]]) -> List[List[int]]:
    #     """
    #     ENTER CODE HERE: complete the code
    #     Viterbi Algorithm: Follow the algorithm in Jim's book:
    #     Figure 8.10 at https://web.stanford.edu/~jurafsky/slp3/8.pdf
    #     """
    #     # store the decoded states here
    #     all_predictions = []
    #     for obs_ids in observation_ids:
    #         T = len(obs_ids)  # Sequence length
    #         viterbi = np.zeros((self.n, T))  # The viterbi table
    #         back_pointer = np.zeros((self.n, T))   # backpointers for each state+sequence id
    #         # TODO: Fill the viterbi table, back_pointer. Get the optimal sequence by backtracking
    #         ...
    #         raise NotImplementedError
    #     return all_predictions

[nltk_data] Downloading package indian to
[nltk_data]     /Users/tylercranmer/nltk_data...
[nltk_data]   Package indian is already up-to-date!


In [13]:
observation = [1,3,1]
pi = [.8, .2]

T = 3
# (hot,cold)
S = 2

viterbi = np.zeros((S, T))
back_pointer = np.zeros((S, T)) 
for i, s in enumerate(pi):
    viterbi[i][0] = pi[i]
viterbi 

array([[0.8, 0. , 0. ],
       [0.2, 0. , 0. ]])

In [16]:
viterbi.shape[0]

2

In [1]:
import numpy as np

# Define the ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Given weights for the network
W1 = np.array([[5, 10, -20], [3, -8, 5]])
W2 = np.array([[1, -1]])

# Given input
input_values = np.array([2, 2, 5])

# Forward pass through the network
# Calculate the input to the hidden layer
hidden_input = np.dot(W1, input_values)

# Apply ReLU activation function
hidden_output = relu(hidden_input)

# Calculate the input to the output layer
output_input = np.dot(W2, hidden_output)

# Apply sigmoid activation function to get the final output
output = sigmoid(output_input)

output


array([3.05902227e-07])

In [2]:
output_input 


array([-15])

In [10]:
print(input_values.shape)
print(W1.shape)
print(W2.shape)
print(hidden_output.shape)

(3,)
(2, 3)
(1, 2)
(2,)


In [13]:
print(input_values)
print(hidden_input)
print(hidden_output)
print(output_input)
print(output)

[2 2 5]
[-70  15]
[ 0 15]
[-15]
[3.05902227e-07]


In [6]:
hidden_output

array([ 0, 15])